// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkB73C5qxrbcfkvWGrQTTqqkDqzANuHLM',
    appId: '1:332591751983:web:ec86437e313a89de9677da',
    messagingSenderId: '332591751983',
    projectId: 'curd-43920',
    authDomain: 'curd-43920.firebaseapp.com',
    storageBucket: 'curd-43920.appspot.com',
    measurementId: 'G-XZ95GGZB9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIn8l9QDWpcK3kH43n0mKKqx3RicVh3J0',
    appId: '1:332591751983:android:8a821c2818399dbb9677da',
    messagingSenderId: '332591751983',
    projectId: 'curd-43920',
    storageBucket: 'curd-43920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlx4A5-q5guUsx0FNKKzt2GB8d_BejsAQ',
    appId: '1:332591751983:ios:8cf0d429522bef879677da',
    messagingSenderId: '332591751983',
    projectId: 'curd-43920',
    storageBucket: 'curd-43920.appspot.com',
    iosBundleId: 'com.example.curd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlx4A5-q5guUsx0FNKKzt2GB8d_BejsAQ',
    appId: '1:332591751983:ios:8cf0d429522bef879677da',
    messagingSenderId: '332591751983',
    projectId: 'curd-43920',
    storageBucket: 'curd-43920.appspot.com',
    iosBundleId: 'com.example.curd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkB73C5qxrbcfkvWGrQTTqqkDqzANuHLM',
    appId: '1:332591751983:web:47b3fad7666edc049677da',
    messagingSenderId: '332591751983',
    projectId: 'curd-43920',
    authDomain: 'curd-43920.firebaseapp.com',
    storageBucket: 'curd-43920.appspot.com',
    measurementId: 'G-G4J7HLFZNT',
  );
}
