// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbkd_y0AX-vYWPD_bKCrGam2IT7wGr2dM',
    appId: '1:840409233089:web:63449cb3dcc412aaa60640',
    messagingSenderId: '840409233089',
    projectId: 'auth-41811',
    authDomain: 'auth-41811.firebaseapp.com',
    storageBucket: 'auth-41811.appspot.com',
    measurementId: 'G-C6WF9HVREQ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgrMdSxBZQH6YGo67j07Jjf5gm9WT9_Dg',
    appId: '1:840409233089:ios:0f5cf671f23ce9f5a60640',
    messagingSenderId: '840409233089',
    projectId: 'auth-41811',
    storageBucket: 'auth-41811.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgrMdSxBZQH6YGo67j07Jjf5gm9WT9_Dg',
    appId: '1:840409233089:ios:0f5cf671f23ce9f5a60640',
    messagingSenderId: '840409233089',
    projectId: 'auth-41811',
    storageBucket: 'auth-41811.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbkd_y0AX-vYWPD_bKCrGam2IT7wGr2dM',
    appId: '1:840409233089:web:b88b299eee6be217a60640',
    messagingSenderId: '840409233089',
    projectId: 'auth-41811',
    authDomain: 'auth-41811.firebaseapp.com',
    storageBucket: 'auth-41811.appspot.com',
    measurementId: 'G-7XGM5HQG1C',
  );
}
